accounts/urls.py
from django.conf.urls import url
from accounts import views

#template URLs
app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.user_login, name='user_login'),

]

bfdworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from accounts import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^qbreport/', include('qbreport.urls', namespace='qb')),
    url(r'^repricing/', include('repricing.urls',namespace='reprice')),
    url(r'^amazon', include('amazonbulletpoints.urls', namespace='amz')),
    url(r'^retailbloom/',include('retailbloom.urls', namespace='bloom'))

]

qbreport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from qbreport import views

app_name = 'qbreport1'


urlpatterns = [
    url(r'^$', views.modelFormUpload, name='upload_QB_File'),
    url(r'^download/(?P<file_name>.+)$', views.send_file, name='download_file'),
    url(r'^download-template/template.csv$', views.download_template, name='download_template'),
    url(r'^vendor-not-in-database/$', views.vendor_not_in_datab , name='vendor_not_in_db')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qbreport/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse

# Create your models here.

class VendorNames(models.Model):
    qbVendorName = models.CharField(max_length=150)
    omxVendorName = models.CharField(max_length=150)

    def __str__(self):
        return self.qbVendorName 
    class Meta:
        verbose_name_plural = 'Vendor Names'

class OMXOrderHistory(models.Model):
    customID = models.CharField(max_length=45)
    orderNumber = models.CharField(max_length=15, null=True)
    itemCode = models.CharField(max_length=16, null=True)
    description = models.CharField(max_length=150, null=True)
    vendorName = models.CharField(max_length=600, null=True)
    dropShipCOG = models.FloatField( null=True)
    qty = models.IntegerField(null=True)
    total = models.FloatField(null=True)

    def __str__(self):
        return self.customID
    class Meta:
        verbose_name_plural = 'OMX Order History'

class QBImportFile(models.Model):
    notes = models.CharField(max_length=25, blank=True, null=True)
    customID = models.CharField(max_length=45)
    invoiceDate = models.DateField(blank=True, null=True)
    vendorName = models.CharField(max_length=45)
    invoiceNumber = models.CharField(max_length=35,null=True, validators=[RegexValidator(r'^\d\d\d\d\d\d-\d\d$')])
    poNumb = models.CharField(max_length=25, null=True, validators=[RegexValidator(r'^\d\d\d\d\d\d-\d\d$')])
    invocieTotal = models.FloatField(blank=True, null=True)
    dropShipFee = models.FloatField(blank=True, null=True)
    shippingFee = models.FloatField(blank=True, null=True)
    omxPO = models.IntegerField(blank=True, null=True)
    omxTotal = models.FloatField(blank=True, null=True)
    totalDifference = models.FloatField(default=None)
    discrepancy = models.CharField(max_length=45, blank=True, null=True)
    memo = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.customID

class UploadFile(models.Model):
    userName = models.ForeignKey('auth.User')
    email = models.EmailField(unique=False)
    orderReport = models.FileField(upload_to='qbreports/uploads/')
    formatedFile = models.FileField(upload_to='qbreports/uploads/', default='qbreports/uploads/test.xlsx')
    uploadDate = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('download_file')

    class Meta:
        verbose_name_plural = 'Uploaded Files'

    def __str__(self):
        return self.orderReport

class NeedToAddVendorToDatabase(models.Model):
    verndorname = models.CharField(max_length=45, blank=True, null=True, unique=True)

    def __str__(self):
        return self.verndorname

qbreport/forms.py
from django import forms
from .models import UploadFile

class DocumenUpload(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ('orderReport',)

qbreport/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView)
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.template import loader
from wsgiref.util import FileWrapper

# Create your views here.
import os
from .custom_code import *
from .forms import DocumenUpload
from .models import UploadFile, VendorNames, OMXOrderHistory, QBImportFile, NeedToAddVendorToDatabase


#View that pulls in the file
def modelFormUpload(request):
    if request.method == 'POST':
        form = DocumenUpload(request.POST, request.FILES)
        if form.is_valid():
            #Function that saves the file with a unique name
            #formats the file to match the QBImportFile Table
            #Then uploads the file data to the database
            UploadedFilePath = handle_uploaded_file(request.FILES['orderReport'])
            QBFile, vendorissue = formatfile(UploadedFilePath)

            if vendorissue:
                return redirect('qb:vendor_not_in_db')
            else:
                uploadToDatabase(QBFile)

            finialFormatedFile = join_Database()

            obj = form.save(commit=False)
            obj.userName = request.user
            obj.formatedFile = finialFormatedFile
            obj.save()

            #saves the user and email address to the UploadFile table
            form.save()

            NewFileName = finialFormatedFile.split('/')

            return redirect('qb:download_file', file_name=NewFileName[-1])

    else:
        form = DocumenUpload()
    return render(request, 'qbreport/uploadfile.html', {
        'form': form
    })


def send_file(request,file_name):
    """
    Send a file through Django without loading the whole file into
    memory at once. The FileWrapper will turn the file object into an
    iterator for chunks of 8KB.
    """
    render(request, 'qbreport/download.html')
    file_path = settings.MEDIA_ROOT +'/qbreports/uploads/'+ file_name
    #filename = 'media/qbreports/uploads/custom_qb_report.xlsx' # Select your file here.
    wrapper = FileWrapper(open(file_path, 'rb'))
    response = HttpResponse(wrapper, content_type='application/vnd.ms-excel')
    response['Content-Length'] = os.path.getsize(file_path)
    print("file pushed for download")
    return response

def download_template(request):
    """
    When the Downloads a template file of the headers need to
    upload a file correctly to the tool
    """
    file_path = settings.MEDIA_ROOT +'/qbreports/uploads/'+ "qb_report_template_file.csv"
    wrapper = FileWrapper(open(file_path, 'rb'))
    response = HttpResponse(wrapper, content_type='text/csv')
    response['Content-Length'] = os.path.getsize(file_path)
    return response


def vendor_not_in_datab(request):
    """
    if a vendor name is not in our database the user will be able to views
    the names of the vendors that need to be added to the Database.
    """

    vendors = NeedToAddVendorToDatabase.objects.all().values()

    return render(request, 'qbreport/new-vendor.html', {'vendors':vendors} )

qbreport/templates/qbreport/download.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}
<div class="container">
<h1> Successful!!! </h1>
<h2>download should start in a few seconds</h2>
</div>
{% endif %}

{% endblock %}

qbreport/templates/qbreport/new-vendor.html
{% extends "accounts/base.html" %}
{% block body_block %}

<div class="container table-container">
  <h2>Vendor Not in Database</h2>
  <p>If a vendor's name is listed below, then they need to be mapped in the database.<br>
  You will need to know the name of the vendor as Black Forest Decor uses it in OMX. <br>
  If you don't know the name of the vendor as it is listed in OMX, please contact the <br>
  warehouse team and request that they send you the name of the vendor in OMX as it is stated <br>
  under "base item attribute 7."  </p>
  <table class="table table-striped file-format table-bordered">
    <tr>
      <td>Vendor:</td>
    </tr>
    {% for vendor in vendors.all  %}
    <tr>
      <td>{{ vendor.verndorname }}</td>
    </tr>

    {% endfor %}

  </table>
</div>

{% endblock %}

qbreport/templates/qbreport/uploadfile.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}
<div class="container form-container">
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Upload</button>
</form>
{% endif %}
</div>

<div class="container table-container">
  <h2>File Header Format:</h2>
  <table class="table table-striped file-format table-bordered">
  <tr>
    <td>Vendor Name</td>
    <td>Invoice &nbsp; Date</td>
    <td>Invoice Number</td>
    <td>Invoice Total</td>
    <td>Drop Ship Fee</td>
    <td>Shipping Fee</td>
    <td>OMX PO</td>
    <td>OMX Total</td>
    <td>PO Num</td>
    <td>Total&nbsp; &nbsp; &nbsp; &nbsp;Difference</td>
    <td>Discrepancy</td>
    <td>Memo</td>
  </tr>
  <tr>
    <td>Westport Linens, Inc</td>
    <td>43096</td>
    <td>104379</td>
    <td>52</td>
    <td>0</td>
    <td>0</td>
    <td>719838</td>
    <td>52</td>
    <td>719838-1</td>
    <td></td>
    <td>PREVIOUSLY DELETED</td>
    <td>WESTPORT LINENS 010918 104379</td>
  </tr>
</table>

</div>

<div class="container">
  <p>Not sure if you have the headers in your file setup correctly?<br>
    Click the Download button below and use that file's headers. </p>
  <a class="btn btn-default" href="{% url 'qbreport1:download_template' %}" role="button">Download Template File</a>
</div>



{% endblock %}