accounts/urls.py
from django.conf.urls import url
from accounts import views

#template URLs
app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.user_login, name='user_login'),

]

amazonbulletpoints/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from amazonbulletpoints import views

app_name = 'amzbullet'


urlpatterns = [
    url(r'^$', views.itemcodeUpload, name='amz_upload_file'),
    url(r'^download/(?P<file_name>.+)$', views.download_template, name='download_file')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bfdworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from accounts import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^qbreport/', include('qbreport.urls', namespace='qb')),
    url(r'^repricing/', include('repricing.urls',namespace='reprice')),
    url(r'^amazon', include('amazonbulletpoints.urls', namespace='amz')),
    url(r'^retailbloom/',include('retailbloom.urls', namespace='bloom'))

]

qbreport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from qbreport import views

app_name = 'qbreport1'


urlpatterns = [
    url(r'^$', views.modelFormUpload, name='upload_QB_File'),
    url(r'^download/(?P<file_name>.+)$', views.send_file, name='download_file'),
    url(r'^download-template/template.csv$', views.download_template, name='download_template'),
    url(r'^vendor-not-in-database/$', views.vendor_not_in_datab , name='vendor_not_in_db')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repricing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from repricing import views

app_name = 'reprice1'


urlpatterns = [
    url(r'^$', views.vendor_id_call, name='findVendorId'),
    url(r'^download/vendor(?P<supplierID>.+)template$', views.download_vendor_file, name='download_vendor_file')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retailbloom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from retailbloom import views

app_name = 'retailbloom1'


urlpatterns = [
    url(r'^$', views.modelFormUpload, name='upload_file'),
    url(r'^validate/(?P<pk>\d+)$',views.validate_page, name='validate_url_page'),
    url(r'^success/(?P<pk>\d+)$', views.upload_to_ftp, name='success_url'),
    url(r'^download-template/sample_file.csv$', views.download_template, name='download_template'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'accounts/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password =  request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account Not Active.  See Your Manager to Gain Access.')

        else:
            print("someone tried to login and failed")
            print('Username: {} and Password: {}'.format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'accounts/login.html', {})

templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
{% load auth_extras %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/master.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">Black Forest Decor Portal</a> </li>
          {% if user.is_authenticated %}
            {% if user.is_superuser or user.is_staff  %}
            <li> <a class="navbar-link" href="{% url 'admin:index' %}">Users</a> </li>
            {% endif %}
            {% if request.user|has_group:"Repricing" or user.is_superuser %}
            <li> <a class="navbar-link" href="{% url 'reprice1:findVendorId' %}">Repricing</a> </li>
            {% endif %}
            {% if request.user|has_group:"QB Reports" or user.is_superuser %}
            <li> <a class="navbar-link" href="{% url 'qbreport1:upload_QB_File' %}">QB Report</a> </li>
            {% endif %}

            {% if request.user|has_group:"amazon" or user.is_superuser %}
            <li> <a class="navbar-link" href="{% url 'amzbullet:amz_upload_file' %}">Amazon Bullet Points</a> </li>
            {% endif %}
            {% if request.user|has_group:"retail_bloom" or user.is_superuser %}
            <li> <a class="navbar-link" href="{% url 'bloom:upload_file' %}">RetailBloom</a> </li>
            {% endif %}
          <li> <a class="navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class="navbar-link" href="{% url 'accounts:user_login' %}">Login</a> </li>
          {% endif %}




        </ul>

      </div>

    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>



  </body>
</html>

templates/accounts/index.html
{% extends "accounts/base.html" %}
{% block body_block %}

{% if user.is_authenticated %}
<div class="jumbotron">
  <h1>Black Forest Decor Workshop</h1>
</div>
{% else %}
  <div id="center-block">


  <h1 class="login-header">Login Form</h1>
  <form  action="{% url 'accounts:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label><br>
    <input type="text" name="username" placeholder="Enter Username">
    <br><br>

    <label for="password">Password:</label><br>
    <input type="password" name="password">
    <br>
    <input type="submit" value="Log in" class="LoginButton">

  </form>

</div>
{% endif %}

{% endblock %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login:</h1>
  <form  action="{% url 'accounts:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" value="Login">

  </form>

</div>

{% endblock %}