accounts/urls.py
from django.conf.urls import url
from accounts import views

#template URLs
app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.user_login, name='user_login'),

]

bfdworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from accounts import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^qbreport/', include('qbreport.urls', namespace='qb')),
    url(r'^repricing/', include('repricing.urls',namespace='reprice')),
    url(r'^amazon', include('amazonbulletpoints.urls', namespace='amz')),
    url(r'^retailbloom/',include('retailbloom.urls', namespace='bloom'))

]

retailbloom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from retailbloom import views

app_name = 'retailbloom1'


urlpatterns = [
    url(r'^$', views.modelFormUpload, name='upload_file'),
    url(r'^validate/(?P<pk>\d+)$',views.validate_page, name='validate_url_page'),
    url(r'^success/(?P<pk>\d+)$', views.upload_to_ftp, name='success_url'),
    url(r'^download-template/sample_file.csv$', views.download_template, name='download_template'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retailbloom/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
# Create your models here.

class RetailBloom(models.Model):
    file_name = models.CharField(max_length=100)
    total_rows = models.IntegerField(null=True)
    uploadDate = models.DateTimeField(default=timezone.now)
    file_location = models.CharField(max_length=100)
    retailbloom_Report = models.FileField(upload_to='retailbloom/uploads/')

    def __str__(self):
        return self.file_name
    class Meta:
        verbose_name_plural = 'Retail Bloom Data'

retailbloom/forms.py
from django import forms
from .models import RetailBloom

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = RetailBloom
        fields = ('retailbloom_Report',)

        widgets = {
            'retailbloom_Report':forms.FileInput(attrs={'class':'Order-Report'}),
        }

retailbloom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView)
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.template import loader
from wsgiref.util import FileWrapper

# Create your views here.
from itertools import islice
import os
from .custom_code import *
from .forms import UploadFileForm
from .models import RetailBloom
from .smtplib_email_notification import *
from ftplib import FTP




ftp = FTP(host=os.environ["dropship_ftp_host"])
ftp.login(user=os.environ["dropship_ftp_user"], passwd=os.environ["dropship_ftp_pass"])
ftp.cwd('/dropshipadministrator2717.com/channelsale2')

def placeFile(f):
    ftp.cwd('/dropshipadministrator2717.com/channelsale2')
    filename = f
    ftp.storbinary('STOR ' + filename, open(filename, 'rb'))
    ftp.rename(f,'retailbloom_price_and_qty.csv')
    ftp.quit()



#View that pulls in the file
def modelFormUpload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            #Function that saves the file with a unique name
            #formats the file to match the QBImportFile Table
            #Then uploads the file data to the database
            fileLocation = handle_uploaded_file(request.FILES['retailbloom_Report'],request.FILES['retailbloom_Report'].name)
            total_rows_in_file = sum(1 for line in request.FILES['retailbloom_Report'])
            fileName = request.FILES['retailbloom_Report'].name

            with open(fileLocation) as myfile:
                head = list(islice(myfile, 1))

            if head[0].rstrip() != 'ItemCode':
                return render(request, 'retailbloom/error.html', {'header':head[0]})

            obj = form.save(commit=False)
            obj.total_rows = total_rows_in_file
            obj.file_location = fileLocation
            obj.file_name = fileName
            obj.save()
            #saves the user and email address to the UploadFile table
            form.save()

            return redirect('bloom:validate_url_page', pk=obj.id)

    else:
        form = UploadFileForm()
    return render(request, 'retailbloom/submit.html', {
        'form': form
    })

def download_template(request):
    """
    When the Downloads a template file of the headers need to
    upload a file correctly to the tool
    """
    file_path = settings.MEDIA_ROOT +'/retailbloom/uploads/'+ "retailbloom_template_file.csv"
    wrapper = FileWrapper(open(file_path, 'rb'))
    response = HttpResponse(wrapper, content_type='text/csv')
    response['Content-Length'] = os.path.getsize(file_path)
    return response


def validate_page(request, pk):
    """
    validates that all the data in the file is uploaded correctly .
    """
    file_details = get_object_or_404(RetailBloom, pk=pk)
    total_rows_in_file = file_details.total_rows
    post_pk = file_details.pk
    fileName = file_details.file_name

    with open(file_details.file_location) as myfile:
        head = list(islice(myfile, 25))

    return render(request, 'retailbloom/validate.html', {'total_rows':total_rows_in_file, 'sample_file': head, 'upload_pk':post_pk, 'file_name':fileName} )

def upload_to_ftp(request, pk):

    file_details = get_object_or_404(RetailBloom, pk=pk)
    fileLocation = file_details.file_location
  
    os.chdir(settings.MEDIA_ROOT  +"/retailbloom/uploads/")

    try:
        placeFile(file_details.file_name)
        send_update_email(email_from='cyle@blackforestdecor.com',
                          email_to='cyle@blackforestdecor.com',
                          subject_line='Retail Bloom File Upload',
                          file_attachment=file_details.file_name,
                          message="RetailBloom's file was successfully poasted to the FTP site.")
    except Exception as e:
        print(e)

    return render(request, 'retailbloom/success.html')

retailbloom/templates/retailbloom/error.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}
<h2>File Header issue:</h2>
<p>You have "{{header}}" as your header value when it should be "ItemCode."</p>
<a class="btn btn-default" href="{% url 'bloom:upload_file'%}" role="button">Return to Upload Page</a><br><br>

{% endif %}
{% endblock %}

retailbloom/templates/retailbloom/submit.html
{% extends "accounts/base.html" %}
{% load staticfiles %}

{% block body_block %}

{% if user.is_authenticated %}

<div class="container retailbloomform">
  <h3>Upload File:</h3>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endif %}
</div>
<br>
<div class="container">
  <h3>Download Sample File:</h3>
  <a class="btn btn-default" href="{% url 'bloom:download_template'%}" role="button">Download Sample File</a><br><br>

</div>
<div class="container">
  <h3>Directions:</h3>
  <ul>
    <li>There should only be one column in the upload file. That column must have the heading <strong>"ItemCode"</strong></li>
    <li>Upload File <strong> MUST</strong> be in a .csv format.</li>
    <li>List <strong>all</strong> the Item Codes of the items you want Channel Advisor to only update the price and quantities for.</li>
    <li>If you are not sure if you are using the correct value for the Item Code, go to our website and search for the product. <br>Then go to that product's product page, and you will be able to confirm the value of the item code.<br>
        <img style="width: 800px; height: 600px;"alt="Image description" src="{% static 'images/productcode.jpg' %}"/>

  </ul>
</div>
{% endblock %}

retailbloom/templates/retailbloom/success.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}
<h2>File Successfully Posted</h2>
{% endif %}
{% endblock %}

retailbloom/templates/retailbloom/validate.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}

<h2>Retail Bloom Upload File: {{file_name}}</h2>
<h3>Total Items in File: {{total_rows}}</h3>

<div class="container">
  {% if upload_pk %}
    <a class="btn btn-default" href="{% url 'bloom:success_url' pk=upload_pk %}" role="button">Post File</a><br><br>

  {% endif %}

</div>
<div class="container table-container">
  <h2>File Preview:</h2>

  <table class="table table-striped file-format table-bordered">
    {% for row in sample_file  %}
      <tr>
        <td>{{ row }}</td>
      </tr>
      {% endfor %}

</table>

</div>
{% endif %}
{% endblock %}