accounts/urls.py
from django.conf.urls import url
from accounts import views

#template URLs
app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.user_login, name='user_login'),

]

bfdworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from accounts import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^qbreport/', include('qbreport.urls', namespace='qb')),
    url(r'^repricing/', include('repricing.urls',namespace='reprice')),
    url(r'^amazon', include('amazonbulletpoints.urls', namespace='amz')),
    url(r'^retailbloom/',include('retailbloom.urls', namespace='bloom'))

]

repricing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from repricing import views

app_name = 'reprice1'


urlpatterns = [
    url(r'^$', views.vendor_id_call, name='findVendorId'),
    url(r'^download/vendor(?P<supplierID>.+)template$', views.download_vendor_file, name='download_vendor_file')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repricing/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.

class RepricingOMXData(models.Model):
    bfdItemCode = models.CharField(max_length=255,null=True,blank=True)
    vendorID = models.PositiveIntegerField(null=True,blank=True)
    vendorCode = models.CharField(max_length=255,null=True,blank=True)
    vendor_UPC = models.CharField(max_length=16, null=True,blank=True)
    vendor_ProductName = models.CharField(max_length=250, null=True,blank=True)
    currWholesalePrice_AD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    newWholesalePrice_AD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    currWholesalePrice_BD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    newWholesalePrice_BD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    currDropShipPrice_AD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    newDropShipPrice_AD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    currDropShipPrice_BD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    newDropShipPrice_BD = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    dropShipFee = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    mapPrice = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    fullRetailPrice_MSRP = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    optionOneValue = models.CharField(max_length=250, null=True,blank=True)
    optionOneSurcharge = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    optionTwoValue = models.CharField(max_length=250, null=True,blank=True)
    optionTwoSurcharge = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)
    optionThreeValue = models.CharField(max_length=250, null=True,blank=True)
    optionThreeSurcharge = models.DecimalField(max_digits=12, decimal_places=2, null=True,blank=True)



    def __str__(self):
        return self.vendor_ProductName

repricing/forms.py
from django import forms
from .models import RepricingOMXData

class VendorIDForm(forms.ModelForm):
    class Meta:
        model = RepricingOMXData
        fields = ('vendorID',)

        widgets = {
            'vendorID':forms.TextInput(attrs={'class':'vendorcss'}),
        }

repricing/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
from wsgiref.util import FileWrapper
from django.conf import settings

import os

from .forms import VendorIDForm
from .models import RepricingOMXData
from .custom_code import *


class FormListView(FormMixin, MultipleObjectMixin, TemplateResponseMixin, View):
    """
     A View which takes a queryset and filters it via a validated form submission
    """
    model = RepricingOMXData
    form_class = VendorIDForm
    template = 'repricing/vendoridsubmit.html'

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        queryset = self.get_queryset()
        vendorNumber = form.cleaned_data['vendorID']
        object_list = RepricingOMXData.objects.filter(vendorID=vendorNumber)
        context = self.get_context_data(vendorID=object_list, form=form)
        return self.render_to_response(context)


def vendor_id_call(request):
    template_name = 'repricing/validate.html'
    model = RepricingOMXData
    form_class = VendorIDForm

    # if request.method == 'POST':
    form = form_class(request.POST)
    if form.is_valid():
        vendor_data = model.objects.filter(vendorID=form.cleaned_data['vendorID'])
        VendorID = form.cleaned_data['vendorID']
        total_rows = model.objects.all()
        row_count = total_rows.count()
    else:
        form = VendorIDForm()
        return render(request, template_name, {
        'form':form
    })

    context = {'form':form, 'VendorData': vendor_data, 'VendorID':VendorID, 'RowCount':row_count}

    return render(request, template_name, context)


def download_vendor_file(request,supplierID):
    """

    """
    template_name = 'repricing/validate.html'
    model = RepricingOMXData
    file_name = settings.MEDIA_ROOT + '/repricing/repricingvendor{}products.csv'.format(supplierID)
    xlsx_file_name = settings.MEDIA_ROOT + '/repricing/repricingvendor{}products.xlsx'.format(supplierID)

    render(request, template_name)

    formated_pd_file = convert_queryset_csv(model.objects.filter(vendorID=supplierID),file_name)
    xlsx_file_name = format_excel_file(formated_pd_file,xlsx_file_name)

    wrapper = FileWrapper(open(xlsx_file_name, 'rb'))
    response = HttpResponse(wrapper, content_type='application/vnd.ms-excel')
    response['Content-Length'] = os.path.getsize(xlsx_file_name)


    return response

repricing/templates/repricing/validate.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}

<h2>Repricing Report:</h2>
<h3>Total Items in Database: {{RowCount}}</h3>
<div class="container vendorform">
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endif %}
</div>

<div class="container table-container">
  <h2>File Preview:</h2>{% if VendorID %}
    <a class="btn btn-default" href="{% url 'reprice:download_vendor_file' supplierID=VendorID %}" role="button">Download</a><br><br>

  {% endif %}
  <table class="table table-striped file-format table-bordered">
    <tr>
      <td>Vendor ID</td>
      <td>Item Code</td>
      <td>Vendor Code</td>
      <td>UPC</td>
      <td>Vendor Product Name</td>
      <td>Current Wholesale Price AD</td>
      <td>New Wholesale Price AD</td>
      <td>Current Wholesale Price BD</td>
      <td>New Wholesale Price BD</td>
      <td>Current DropShip Price AD</td>
      <td>New DropShip Price AD</td>
      <td>Current DropShip Price BD</td>
      <td>New DropShip Price BD</td>
      <td>DropShip Fee</td>
      <td>MAP</td>
      <td>Full Retail Price MSRP</td>
      <td>Option One Value</td>
      <td>Option One Surcharge</td>
      <td>Option Two Value</td>
      <td>Option Two Surcharge</td>
      <td>Option Three Value</td>
      <td>Option Three Surcharge</td>
    </tr>
    {% for row in VendorData.all  %}
    {% if forloop.counter < 11 %}
      <tr>
        {% if row.vendorID == None %}
        <td></td>
        {% else %}
        <td>{{ row.vendorID }}</td>
        {% endif %}

        {% if row.bfdItemCode == None %}
        <td></td>
        {% else %}
        <td>{{ row.bfdItemCode }}</td>
        {% endif %}

        {% if row.vendorCode == None %}
        <td></td>
        {% else %}
        <td>{{ row.vendorCode }}</td>
        {% endif %}

        {% if row.vendor_UPC == None %}
        <td></td>
        {% else %}
        <td>{{ row.vendor_UPC }}</td>
        {% endif %}

        {% if row.vendor_ProductName == None %}
        <td></td>
        {% else %}
        <td>{{ row.vendor_ProductName }}</td>
        {% endif %}

        {% if row.currWholesalePrice_AD == None %}
        <td></td>
        {% else %}
        <td>{{ row.currWholesalePrice_AD }}</td>
        {% endif %}

        {% if row.newWholesalePrice_AD == None %}
        <td></td>
        {% else %}
        <td>{{ row.newWholesalePrice_AD }}</td>
        {% endif %}

        {% if row.currWholesalePrice_BD == None %}
        <td></td>
        {% else %}
        <td>{{ row.currWholesalePrice_BD }}</td>
        {% endif %}

        {% if row.newWholesalePrice_BD == None %}
        <td></td>
        {% else %}
        <td>{{ row.newWholesalePrice_BD }}</td>
        {% endif %}

        {% if row.currDropShipPrice_AD == None %}
        <td></td>
        {% else %}
        <td>{{ row.currDropShipPrice_AD }}</td>
        {% endif %}

        {% if row.newDropShipPrice_AD == None %}
        <td></td>
        {% else %}
        <td>{{ row.newDropShipPrice_AD }}</td>
        {% endif %}

        {% if row.currDropShipPrice_BD == None %}
        <td></td>
        {% else %}
        <td>{{ row.currDropShipPrice_BD }}</td>
        {% endif %}

        {% if row.newDropShipPrice_BD == None %}
        <td></td>
        {% else %}
        <td>{{ row.newDropShipPrice_BD }}</td>
        {% endif %}

        {% if row.dropShipFee == None %}
        <td></td>
        {% else %}
        <td>{{ row.dropShipFee }}</td>
        {% endif %}

        {% if row.mapPrice == None %}
        <td></td>
        {% else %}
        <td>{{ row.mapPrice }}</td>
        {% endif %}

        {% if row.fullRetailPrice_MSRP == None %}
        <td></td>
        {% else %}
        <td>{{ row.fullRetailPrice_MSRP }}</td>
        {% endif %}

        {% if row.optionOneValue == None %}
        <td></td>
        {% else %}
        <td>{{ row.optionOneValue }}</td>
        {% endif %}

        {% if row.optionOneSurcharge == None %}
        <td></td>
        {% else %}
        <td>{{ row.optionOneSurcharge }}</td>
        {% endif %}

        {% if row.optionTwoValue == None %}
        <td></td>
        {% else %}
        <td>{{ row.optionTwoValue }}</td>
        {% endif %}

        {% if row.optionTwoSurcharge == None %}
        <td></td>
        {% else %}
        <td>{{ row.optionTwoSurcharge }}</td>
        {% endif %}

        {% if row.optionThreeValue == None %}
        <td></td>
        {% else %}
        <td>{{ row.optionThreeValue }}</td>
        {% endif %}

        {% if row.optionThreeSurcharge == None %}
        <td></td>
        {% else %}
        <td>{{ row.optionThreeSurcharge }}</td>
        {% endif %}

      </tr>
      {% endif %}
      {% endfor %}

</table>

</div>

{% endblock %}

repricing/templates/repricing/vendoridsubmit.html
{% extends "accounts/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}
<div class="container vendorform">
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endif %}
</div>

{% endblock %}